# Generated by Django 5.1 on 2025-07-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockName',
            fields=[
                ('b_id', models.CharField(max_length=10)),
                ('b_name', models.CharField(max_length=100)),
                ('b_land_Ac', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PerDecimal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('b_des', models.CharField(max_length=100)),
                ('bso_email', models.EmailField(max_length=40)),
                ('state', models.CharField(max_length=20)),
                ('rlpay_day', models.CharField(max_length=20)),
                ('land_update', models.DecimalField(decimal_places=2, max_digits=10)),
                ('division', models.CharField(max_length=20)),
                ('emailst', models.EmailField(max_length=40)),
                ('com_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
