# Generated by Django 5.1 on 2025-09-11 17:31

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectAdmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_email', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadExp',
            fields=[
                ('head_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('head_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonExp',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_day', models.DateField()),
                ('esubcode', models.CharField(max_length=50)),
                ('ex_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EDescribe', models.TextField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='commonexp_pics/')),
                ('myuser', models.CharField(max_length=100)),
                ('mm', models.IntegerField()),
                ('rtime', models.DateTimeField(default=account.models.current_local_datetime)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('ExpdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.employee')),
                ('dy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.dealingyear')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'db_table': 'commonexp',
            },
        ),
        migrations.CreateModel(
            name='BlockName',
            fields=[
                ('b_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=100, unique=True)),
                ('b_land_Ac', models.FloatField()),
                ('PerDecimal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('b_des', models.TextField(blank=True, null=True)),
                ('bso_email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=10)),
                ('rlpay_day', models.CharField(default='Sunday', max_length=50)),
                ('land_update', models.DecimalField(decimal_places=2, max_digits=10)),
                ('division', models.CharField(choices=[('AC', 'Account'), ('SP', 'Seed Production'), ('SM', 'Seed Marketing')], default='AC', max_length=20)),
                ('emailst', models.EmailField(max_length=254)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abrief', models.CharField(max_length=200)),
                ('target_file', models.FileField(upload_to='advance_files/')),
                ('rtime', models.DateTimeField(auto_now=True)),
                ('entrier', models.CharField(default='admin_user', max_length=20)),
                ('byear', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.dealingyear')),
                ('receiver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.employee')),
                ('com_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='SubHead',
            fields=[
                ('sub_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('subhead_name', models.CharField(max_length=100, unique=True)),
                ('sub_hcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.headexp')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Stop', 'Stop'), ('On', 'On'), ('Abuse', 'Abuse')], default='On', max_length=40)),
                ('allowed_app', models.CharField(choices=[('account', 'Account'), ('block', 'Block'), ('marketing', 'Marketing'), ('contract_grower', 'Contract_grower'), ('ProjectAdmin', 'ProjectAdmin')], max_length=100)),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.blockname')),
                ('byear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.dealingyear')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
