# Generated by Django 5.1 on 2025-09-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0004_company_alter_catagory_comid_and_more'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='com_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.company'),
        ),
        migrations.AlterField(
            model_name='blockname',
            name='com_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.company'),
        ),
        migrations.AlterField(
            model_name='commonexp',
            name='com_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='com_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
