# Generated by Django 5.1 on 2025-07-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('com_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
