# Generated by Django 5.1 on 2025-07-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_company_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='com_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
