# Generated by Django 5.1 on 2025-07-18 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_company_com_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockname',
            name='b_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blockname',
            name='com_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
