# Generated by Django 5.1 on 2025-07-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_blockname_b_id_alter_blockname_com_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockname',
            name='state',
            field=models.CharField(default='ON', max_length=20),
        ),
    ]
