# Generated by Django 5.1 on 2025-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_blockname_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blockname',
            name='b_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blockname',
            name='rlpay_day',
            field=models.CharField(default='Sunday', max_length=20),
        ),
    ]
