# Generated by Django 5.1 on 2025-08-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_company_is_active_alter_blockname_b_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonExp',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_day', models.DateField()),
                ('esubcode', models.CharField(max_length=50)),
                ('ex_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EDescribe', models.TextField()),
                ('ExpdBy', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='commonexp_pics/')),
                ('b_id', models.IntegerField()),
                ('myuser', models.CharField(max_length=100)),
                ('mm', models.IntegerField()),
                ('rtime', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('dy', models.IntegerField()),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'db_table': 'commonexp',
            },
        ),
    ]
