# Generated by Django 5.1 on 2025-08-05 19:02

import account.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0006_alter_dealingyear_dy_session'),
        ('account', '0008_commonexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonexp',
            name='ExpdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.employee'),
        ),
        migrations.AlterField(
            model_name='commonexp',
            name='b_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.blockname'),
        ),
        migrations.AlterField(
            model_name='commonexp',
            name='dy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.dealingyear'),
        ),
        migrations.AlterField(
            model_name='commonexp',
            name='rtime',
            field=models.DateTimeField(default=account.models.current_local_datetime),
        ),
        migrations.AlterField(
            model_name='commonexp',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
