# Generated by Django 5.1 on 2025-08-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_commonexp_expdby_alter_commonexp_b_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name', models.CharField(max_length=100)),
                ('head_code', models.CharField(max_length=20)),
            ],
        ),
    ]
