# Generated by Django 5.1 on 2025-08-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_headexp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headexp',
            name='id',
        ),
        migrations.AlterField(
            model_name='headexp',
            name='head_code',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='headexp',
            name='head_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SubHeadExp',
            fields=[
                ('suhead_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('subhead_name', models.CharField(max_length=100)),
                ('sub_hcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.headexp')),
            ],
        ),
    ]
