# Generated by Django 5.1 on 2025-08-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_headexp_id_alter_headexp_head_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headexp',
            name='head_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='headexp',
            name='head_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subheadexp',
            name='subhead_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
