# Generated by Django 5.1 on 2025-08-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
