# Generated by Django 5.1 on 2025-08-08 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0006_alter_dealingyear_dy_session'),
        ('account', '0014_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Stop', 'Stop'), ('On', 'On'), ('Abuse', 'Abuse')], default='On', max_length=40)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.blockname')),
                ('byear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.dealingyear')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.employee')),
            ],
        ),
    ]
