# Generated by Django 5.1 on 2025-08-10 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0009_remove_dealingyear_dysl_and_more'),
        ('account', '0015_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=20)),
                ('receiver', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abrief', models.CharField(max_length=200)),
                ('target_file', models.FileField(upload_to='')),
                ('rtime', models.DateTimeField(auto_now=True)),
                ('byear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.dealingyear')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
    ]
