# Generated by Django 5.1 on 2025-08-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0009_remove_dealingyear_dysl_and_more'),
        ('account', '0016_advance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.employee'),
        ),
    ]
