# Generated by Django 5.1 on 2025-08-10 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0009_remove_dealingyear_dysl_and_more'),
        ('account', '0017_alter_advance_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='entrier',
            field=models.CharField(default='admin_user', max_length=20),
        ),
        migrations.AlterField(
            model_name='advance',
            name='byear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.dealingyear'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='com_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='advance',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.employee'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='target_file',
            field=models.FileField(upload_to='advance_files/'),
        ),
    ]
