# Generated by Django 5.1 on 2025-08-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_advance_entrier_alter_advance_byear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='b_id',
        ),
        migrations.RemoveField(
            model_name='commonexp',
            name='b_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='byear',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='com_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userid',
        ),
        migrations.DeleteModel(
            name='BlockName',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
