# Generated by Django 5.1 on 2025-08-20 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_userprofile_b_id_remove_commonexp_b_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.CharField(max_length=10, unique=True)),
                ('b_name', models.CharField(max_length=100)),
                ('b_land_Ac', models.FloatField()),
                ('PerDecimal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('b_des', models.TextField(blank=True, null=True)),
                ('bso_email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=10)),
                ('rlpay_day', models.CharField(default='Sunday', max_length=50)),
                ('land_update', models.DecimalField(decimal_places=2, max_digits=10)),
                ('division', models.CharField(choices=[('AC', 'Account'), ('SP', 'Seed Production'), ('SM', 'Seed Marketing')], default='AC', max_length=20)),
                ('emailst', models.EmailField(max_length=254)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
    ]
