# Generated by Django 5.1 on 2025-08-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='block',
            new_name='block_id',
        ),
    ]
