# Generated by Django 5.1 on 2025-08-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_rename_block_userprofile_block_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
