# Generated by Django 5.1 on 2025-08-22 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0009_remove_dealingyear_dysl_and_more'),
        ('account', '0023_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Stop', 'Stop'), ('On', 'On'), ('Abuse', 'Abuse')], default='On', max_length=40)),
                ('allowed_app', models.CharField(choices=[('account', 'Account'), ('block', 'Block'), ('mk', 'Marketing'), ('cg', 'Contract_grower'), ('projectadmin', 'ProjectAdmin')], max_length=50)),
                ('block_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.blockname')),
                ('byear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectAdmin.dealingyear')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.employee')),
            ],
        ),
    ]
