# Generated by Django 5.1 on 2025-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockname',
            name='b_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allowed_app',
            field=models.CharField(choices=[('account', 'account'), ('block', 'Block'), ('marketing', 'Marketing'), ('contract_grower', 'Contract_grower'), ('ProjectAdmin', 'ProjectAdmin')], max_length=50),
        ),
    ]
