# Generated by Django 5.1 on 2025-08-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_userprofile_allowed_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allowed_app',
            field=models.CharField(choices=[('account', 'Account'), ('block', 'Block'), ('marketing', 'Marketing'), ('contract_grower', 'Contract_grower'), ('ProjectAdmin', 'ProjectAdmin')], max_length=100),
        ),
    ]
