# Generated by Django 5.1 on 2025-09-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0012_alter_catagory_catagoryname_and_more'),
        ('account', '0027_alter_userprofile_allowed_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.employee'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='block_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.blockname'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='byear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.dealingyear'),
        ),
        migrations.CreateModel(
            name='SubHead',
            fields=[
                ('sub_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('subhead_name', models.CharField(max_length=100, unique=True)),
                ('sub_hcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.headexp')),
            ],
        ),
        migrations.DeleteModel(
            name='SubHeadExp',
        ),
    ]
