# Generated by Django 5.1 on 2025-09-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectAdmin', '0012_alter_catagory_catagoryname_and_more'),
        ('account', '0028_remove_userprofile_userid_userprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('describe', models.TextField()),
                ('byear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.dealingyear')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
    ]
