# Generated by Django 5.1 on 2025-09-11 17:31

import block.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectAdmin', '0001_initial'),
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=20)),
                ('person_id', models.CharField(max_length=30)),
                ('nid_no', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=14)),
                ('address', models.TextField()),
                ('person_picture', models.ImageField(blank=True, null=True, upload_to=block.models.person_picture_upload_path)),
                ('person_nid_picture', models.ImageField(blank=True, null=True, upload_to=block.models.person_nid_picture_upload_path)),
                ('com_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catagory_short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.catagory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('catagory_short', 'mobile_no')},
            },
        ),
        migrations.CreateModel(
            name='LandMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edate', models.DateField()),
                ('b_id', models.CharField(max_length=20)),
                ('plot_no', models.CharField(max_length=100)),
                ('length1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deci', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=100)),
                ('com_id', models.CharField(max_length=20)),
                ('llid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.person')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=20)),
                ('byear', models.CharField(max_length=20)),
                ('com_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subhead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('block_id', 'sub_code', 'byear', 'com_id', 'user')},
            },
        ),
    ]
