# Generated by Django 5.1 on 2025-09-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_date', models.DateField()),
                ('b_id', models.CharField(max_length=20)),
                ('chalan_no', models.CharField(max_length=20)),
                ('seed_sent', models.IntegerField()),
                ('seed_received', models.IntegerField(default=0)),
                ('empty_bags', models.IntegerField(default=0)),
                ('variety_name', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('day', models.CharField(max_length=20)),
                ('com_id', models.IntegerField()),
            ],
        ),
    ]
