# Generated by Django 5.1 on 2025-09-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_seedtransport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedtransport',
            name='com_id',
            field=models.CharField(max_length=20),
        ),
    ]
