# Generated by Django 5.1 on 2025-09-06 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0028_remove_userprofile_userid_userprofile_employee_id_and_more'),
        ('block', '0002_delete_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=20)),
                ('byear', models.CharField(max_length=20)),
                ('com_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subhead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('block_id', 'sub_code', 'byear', 'com_id', 'user')},
            },
        ),
    ]
