# Generated by Django 5.1 on 2025-09-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_alter_seedtransport_com_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedtransport',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
