# Generated by Django 5.1 on 2025-09-06 15:30

import block.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0012_alter_catagory_catagoryname_and_more'),
        ('block', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=20)),
                ('person_id', models.CharField(max_length=30)),
                ('nid_no', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=14)),
                ('address', models.TextField()),
                ('person_picture', models.ImageField(blank=True, null=True, upload_to=block.models.person_picture_upload_path)),
                ('person_nid_picture', models.ImageField(blank=True, null=True, upload_to=block.models.person_nid_picture_upload_path)),
                ('com_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catagory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.catagory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
