# Generated by Django 5.1 on 2025-09-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_alter_seedtransport_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedtransport',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedtransport',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
