# Generated by Django 5.1 on 2025-09-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_userprofile_userid_userprofile_employee_id_and_more'),
        ('block', '0004_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='catagory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subhead'),
        ),
    ]
