# Generated by Django 5.1 on 2025-09-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_alter_person_catagory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='catagory_id',
            new_name='catagory_short',
        ),
    ]
