# Generated by Django 5.1 on 2025-09-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0005_hvariety'),
        ('block', '0005_alter_seedtransport_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedtransport',
            name='variety_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.hvariety'),
        ),
    ]
