# Generated by Django 5.1 on 2025-09-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0015_catagory'),
        ('block', '0006_rename_catagory_id_person_catagory_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='sub_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.catagory'),
        ),
    ]
