# Generated by Django 5.1 on 2025-09-06 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0015_catagory'),
        ('account', '0028_remove_userprofile_userid_userprofile_employee_id_and_more'),
        ('block', '0007_alter_budget_sub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='sub_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subhead'),
        ),
        migrations.AlterField(
            model_name='person',
            name='catagory_short',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.catagory'),
        ),
    ]
