# Generated by Django 5.1 on 2025-09-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0015_catagory'),
        ('block', '0008_alter_budget_sub_code_alter_person_catagory_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edate', models.DateField()),
                ('b_id', models.IntegerField()),
                ('plot_no', models.CharField(max_length=100)),
                ('llid', models.IntegerField()),
                ('length1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deci', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=100)),
                ('com_id', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('catagory_short', 'mobile_no')},
        ),
    ]
