# Generated by Django 5.1 on 2025-09-10 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0009_landmeasure_alter_person_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmeasure',
            name='llid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.person'),
        ),
    ]
