# Generated by Django 5.1 on 2025-09-11 17:31

import ProjectAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('catagoryid', models.AutoField(primary_key=True, serialize=False)),
                ('catagoryName', models.CharField(max_length=100, unique=True)),
                ('catagory_short', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealingYear',
            fields=[
                ('dy_session', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('busy_status', models.CharField(choices=[('Stop', 'Stop'), ('On', 'On'), ('Abuse', 'Abuse')], default='On', max_length=10)),
            ],
            options={
                'db_table': 'dealing_year',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=100)),
                ('EmpDesig', models.CharField(max_length=100)),
                ('EmpMobile', models.CharField(max_length=15, unique=True)),
                ('EmpEmail', models.EmailField(max_length=50, unique=True)),
                ('EmpBirthDate', models.DateField()),
                ('EmpJoininghDate', models.DateField()),
                ('EmpDiv', models.CharField(max_length=15)),
                ('EmpPicture', models.ImageField(blank=True, null=True, upload_to=ProjectAdmin.models.employee_picture_upload_path)),
                ('EmpStatus', models.CharField(default='ON', max_length=10)),
            ],
        ),
    ]
