# Generated by Django 5.1 on 2025-07-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=100)),
                ('EmpDesi', models.CharField(max_length=50)),
                ('EmpMobile', models.CharField(max_length=15)),
                ('EmpEmail', models.EmailField(max_length=50)),
                ('EmpBirthDate', models.DateField()),
                ('EmpJoininghDate', models.DateField()),
                ('EmpDiv', models.CharField(max_length=15)),
                ('EmpPicture', models.ImageField(upload_to='')),
                ('EmpStatus', models.CharField(max_length=10)),
                ('EmpComId', models.CharField(max_length=10)),
            ],
        ),
    ]
