# Generated by Django 5.1 on 2025-07-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='EmpDesi',
        ),
        migrations.AddField(
            model_name='employee',
            name='EmpDesig',
            field=models.CharField(default='Not Specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpPicture',
            field=models.ImageField(blank=True, null=True, upload_to='img/employee_pictures/'),
        ),
    ]
