# Generated by Django 5.1 on 2025-07-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0002_remove_employee_empdesi_employee_empdesig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpStatus',
            field=models.CharField(default='ON', max_length=10),
        ),
    ]
