# Generated by Django 5.1 on 2025-09-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='EmpDiv',
        ),
    ]
