# Generated by Django 5.1 on 2025-09-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0003_remove_employee_empdiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('com_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_email', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='catagory',
            name='ComId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.company'),
        ),
        migrations.AlterField(
            model_name='dealingyear',
            name='com_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpComId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.company'),
        ),
    ]
