# Generated by Django 5.1 on 2025-07-19 16:45

import ProjectAdmin.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0003_alter_employee_empstatus'),
        ('account', '0007_company_is_active_alter_blockname_b_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpComId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpPicture',
            field=models.ImageField(blank=True, null=True, upload_to=ProjectAdmin.models.employee_picture_upload_path),
        ),
    ]
