# Generated by Django 5.1 on 2025-08-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0004_alter_employee_empcomid_alter_employee_emppicture'),
        ('account', '0008_commonexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpEmail',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpMobile',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='DealingYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dysl', models.CharField(max_length=20)),
                ('dy_session', models.CharField(max_length=20)),
                ('busy_status', models.BooleanField(default=False)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'db_table': 'dealing_year',
            },
        ),
    ]
