# Generated by Django 5.1 on 2025-09-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0004_company_alter_catagory_comid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hvariety',
            fields=[
                ('hvariety_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hvariety_name', models.CharField(max_length=50)),
                ('contract_company', models.CharField(max_length=100)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAdmin.company')),
            ],
        ),
    ]
