# Generated by Django 5.1 on 2025-08-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0005_alter_employee_empemail_alter_employee_empmobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealingyear',
            name='dy_session',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
