# Generated by Django 5.1 on 2025-08-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0006_alter_dealingyear_dy_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealingyear',
            name='id',
        ),
        migrations.AlterField(
            model_name='dealingyear',
            name='dy_session',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
