# Generated by Django 5.1 on 2025-08-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0007_remove_dealingyear_id_alter_dealingyear_dy_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealingyear',
            name='busy_status',
            field=models.BooleanField(choices=[('Stop', 'Stop'), ('On', 'On'), ('Abuse', 'Abuse')], default=False),
        ),
    ]
