# Generated by Django 5.1 on 2025-08-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0008_alter_dealingyear_busy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealingyear',
            name='dysl',
        ),
        migrations.AlterField(
            model_name='dealingyear',
            name='busy_status',
            field=models.CharField(choices=[('Stop', 'Stop'), ('On', 'On'), ('Abuse', 'Abuse')], default='On', max_length=10),
        ),
    ]
