# Generated by Django 5.1 on 2025-08-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0009_remove_dealingyear_dysl_and_more'),
        ('account', '0027_alter_userprofile_allowed_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagoryid', models.CharField(max_length=20)),
                ('catagoryName', models.CharField(max_length=100)),
                ('ComId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
    ]
