# Generated by Django 5.1 on 2025-08-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0010_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='id',
        ),
        migrations.AlterField(
            model_name='catagory',
            name='catagoryid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
