# Generated by Django 5.1 on 2025-08-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0011_remove_catagory_id_alter_catagory_catagoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='catagoryName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='catagoryid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
