# Generated by Django 5.1 on 2025-09-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0012_alter_catagory_catagoryname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='ComId',
        ),
    ]
