# Generated by Django 5.1 on 2025-09-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0013_remove_catagory_comid'),
        ('block', '0005_alter_person_catagory_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
