# Generated by Django 5.1 on 2025-09-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0014_delete_catagory'),
        ('account', '0028_remove_userprofile_userid_userprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('catagoryid', models.AutoField(primary_key=True, serialize=False)),
                ('catagoryName', models.CharField(max_length=100, unique=True)),
                ('catagoryshort', models.CharField(max_length=20, unique=True)),
                ('ComId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
    ]
