# Generated by Django 5.1 on 2025-09-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAdmin', '0015_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='catagoryshort',
            new_name='catagory_short',
        ),
    ]
